"""
This type stub file was generated by pyright.
"""

from pyomo.opt.parallel.async_solver import AsynchronousActionManager, AsynchronousSolverManager, Factory, SolverManagerFactory
from pyomo.opt.parallel import local, manager

