"""
This type stub file was generated by pyright.
"""

from pyomo.core import TransformationFactory
from pyomo.core.plugins.transform.hierarchy import NonIsomorphicTransformation
from pyomo.common.config import ConfigBlock

def target_list(x): # -> list[ComponentUID] | list[Any]:
    ...

logger = ...
@TransformationFactory.register('core.add_slack_variables', doc="Create a model where we add slack variables to every constraint " "and add new objective penalizing the sum of the slacks")
class AddSlackVariables(NonIsomorphicTransformation):
    """
    This plugin adds slack variables to every constraint or to the constraints
    specified in targets.
    """
    CONFIG = ConfigBlock("core.add_slack_variables")
    def __init__(self, **kwds) -> None:
        ...
    


