"""
This type stub file was generated by pyright.
"""

from pyomo.core.base import Transformation, TransformationFactory

logger = ...
@TransformationFactory.register('core.expand_connectors', doc="Expand all connectors in the model to simple constraints")
class ExpandConnectors(Transformation):
    ...


