"""
This type stub file was generated by pyright.
"""

from pyomo.core.base import Transformation

class AbstractTransformation(Transformation):
    """
    Base class for all model transformations that produce abstract
    models.
    """
    def __init__(self, **kwds) -> None:
        ...
    


class ConcreteTransformation(Transformation):
    """
    Base class for all model transformations that produce concrete
    models.
    """
    def __init__(self, **kwds) -> None:
        ...
    


class IsomorphicTransformation(Transformation):
    """
    Base class for 'lossless' transformations for which a bijective
    mapping between optimal variable values and the optimal cost
    exists.
    """
    def __init__(self, **kwds) -> None:
        ...
    


class LinearTransformation(Transformation):
    """Base class for all linear model transformations."""
    def __init__(self, **kwds) -> None:
        ...
    


class NonIsomorphicTransformation(Transformation):
    """
    Base class for 'lossy' transformations for which a bijective
    mapping between optimal variable values and the optimal cost does
    not  exist.
    """
    def __init__(self, **kwds) -> None:
        ...
    


class NonlinearTransformation(Transformation):
    """Base class for all nonlinear model transformations."""
    def __init__(self, **kwds) -> None:
        ...
    


