"""
This type stub file was generated by pyright.
"""

def collectAbstractComponents(model): # -> dict[Any, Any]:
    """
    Returns all abstract constraints, objectives, variables,
    parameters, and sets. Does not query instance values, if
    present. Returns nested dictionaries describing the model,
    including all rules, domains, bounds, and index sets.
    """
    ...

def partial(*args, **kwargs): # -> Callable[..., Any]:
    """
    copy.deepcopy balks at copying anonymous functions. This overrides
    the default behavior of functools.partial to make deepcopy return
    the function itself, rather than attempting to copy it.
    """
    ...

def process_canonical_repn(expr): # -> dict[Any, Any]:
    """
    Returns a dictionary of {var_name_or_None: coef} values. None
    indicates a numeric constant.
    """
    ...

