"""
This type stub file was generated by pyright.
"""

logger = ...
def display(obj, ostream=...): # -> None:
    """Display data in a Pyomo object"""
    ...

def create_name(name, ndx):
    """Create a canonical name for a component using the given index"""
    ...

def apply_indexed_rule(obj, rule, model, index, options=...):
    ...

def apply_parameterized_indexed_rule(obj, rule, model, param, index):
    ...

