"""
This type stub file was generated by pyright.
"""

def symbol_map_from_instance(instance): # -> SymbolMap:
    """
    Create a symbol map from an instance using name-based labelers.
    """
    ...

