"""
This type stub file was generated by pyright.
"""

def is_functor(obj): # -> TypeIs[FunctionType] | bool:
    """
    Returns true iff obj.__call__ is defined.
    """
    ...

def flatten_tuple(x): # -> tuple[Any, ...] | tuple[Any]:
    """
    This wraps around normalize_index. It flattens a nested sequence into
    a single tuple and always returns a tuple, even for single
    element inputs.

    Returns
    -------
    tuple

    """
    ...

