"""
This type stub file was generated by pyright.
"""

from pyomo.core.expr.visitor import ExpressionValueVisitor

class DifferentiationException(Exception):
    ...


_unary_map = ...
_diff_map = ...
class _LeafToRootVisitor(ExpressionValueVisitor):
    def __init__(self, val_dict, der_dict, expr_list, numeric=...) -> None:
        """
        Parameters
        ----------
        val_dict: ComponentMap
        der_dict: ComponentMap
        """
        ...
    
    def visit(self, node, values):
        ...
    
    def visiting_potential_leaf(self, node): # -> tuple[Literal[True], Any] | tuple[Literal[True], Any | None] | tuple[Literal[False], None]:
        ...
    


def reverse_ad(expr):
    """
    First order reverse automatic differentiation

    Parameters
    ----------
    expr: pyomo.core.expr.numeric_expr.NumericExpression
        expression to differentiate

    Returns
    -------
    ComponentMap
        component_map mapping variables to derivatives with respect
        to the corresponding variable
    """
    ...

def reverse_sd(expr):
    """
    First order reverse symbolic differentiation

    Parameters
    ----------
    expr: pyomo.core.expr.numeric_expr.NumericExpression
        expression to differentiate

    Returns
    -------
    ComponentMap
        component_map mapping variables to derivatives with respect
        to the corresponding variable
    """
    ...

