"""
This type stub file was generated by pyright.
"""

ProblemConverterFactory = ...
def convert_problem(args, target_problem_type, valid_problem_types, has_capability=..., **kwds): # -> tuple[Any, Any, None] | tuple[Any, Any, Any]:
    """
    Convert a problem, defined by the 'args' tuple, into another
    problem.
    """
    ...

