"""
This type stub file was generated by pyright.
"""

"""
Management of Pyomo commands
"""
logger = ...
registry = ...
def pyomo_command(name=..., doc=...): # -> Callable[..., Any | None]:
    ...

def get_pyomo_commands(): # -> dict[Any, Any]:
    ...

