"""
This type stub file was generated by pyright.
"""

class Factory:
    """
    A class that is used to define a factory for objects.

    Factory objects may be cached for future use.
    """
    def __init__(self, description=...) -> None:
        ...
    
    def __call__(self, name, **kwds): # -> None:
        ...
    
    def __iter__(self): # -> Generator[Any, Any, None]:
        ...
    
    def __contains__(self, name): # -> bool:
        ...
    
    def get_class(self, name):
        ...
    
    def doc(self, name):
        ...
    
    def unregister(self, name): # -> None:
        ...
    
    def register(self, name, doc=...): # -> Callable[..., Any]:
        ...
    


