"""
This type stub file was generated by pyright.
"""

class __PauseGCCompanion:
    def __init__(self) -> None:
        ...
    


PauseGCCompanion: __PauseGCCompanion = ...
class PauseGC:
    __slots__ = ...
    def __init__(self) -> None:
        ...
    
    def __enter__(self): # -> Self:
        ...
    
    def __exit__(self, type, value, traceback): # -> None:
        ...
    
    def close(self): # -> None:
        ...
    


