"""
This type stub file was generated by pyright.
"""

import typing

_overloads = ...
def overload(func: typing.Callable): # -> Callable[..., Any]:
    """Wrap typing.overload that remembers the overloaded signatures

    This provides a custom implementation of typing.overload that
    remembers the overloaded signatures so that they are available for
    runtime inspection.

    """
    ...

def get_overloads_for(func: typing.Callable):
    ...

