"""
This type stub file was generated by pyright.
"""

from pyomo.common.autoslots import AutoSlots

class PyomoObject(AutoSlots.Mixin):
    __slots__ = ...
    def is_component_type(self): # -> Literal[False]:
        """Return True if this class is a Pyomo component"""
        ...
    
    def is_numeric_type(self): # -> Literal[False]:
        """Return True if this class is a Pyomo numeric object"""
        ...
    
    def is_parameter_type(self): # -> Literal[False]:
        """Return False unless this class is a parameter object"""
        ...
    
    def is_variable_type(self): # -> Literal[False]:
        """Return False unless this class is a variable object"""
        ...
    
    def is_expression_type(self, expression_system=...): # -> Literal[False]:
        """Return True if this numeric value is an expression"""
        ...
    
    def is_named_expression_type(self): # -> Literal[False]:
        """Return True if this numeric value is a named expression"""
        ...
    
    def is_logical_type(self): # -> Literal[False]:
        """Return True if this class is a Pyomo Boolean object.

        Boolean objects include constants, variables, or logical expressions.
        """
        ...
    
    def is_reference(self): # -> Literal[False]:
        """Return True if this object is a reference."""
        ...
    


