"""
This type stub file was generated by pyright.
"""

logger = ...
_virtual_sets = ...
class RealSet:
    @staticmethod
    def get_interval(): # -> tuple[None, None, Literal[0]]:
        ...
    
    @staticmethod
    def is_continuous(): # -> Literal[True]:
        ...
    
    @staticmethod
    def is_integer(): # -> Literal[False]:
        ...
    
    @staticmethod
    def is_binary(): # -> Literal[False]:
        ...
    


class IntegerSet:
    @staticmethod
    def get_interval(): # -> tuple[None, None, Literal[1]]:
        ...
    
    @staticmethod
    def is_continuous(): # -> Literal[False]:
        ...
    
    @staticmethod
    def is_integer(): # -> Literal[True]:
        ...
    
    @staticmethod
    def is_binary(): # -> Literal[False]:
        ...
    


class BinarySet:
    @staticmethod
    def get_interval(): # -> tuple[Literal[0], Literal[1], Literal[1]]:
        ...
    
    @staticmethod
    def is_continuous(): # -> Literal[False]:
        ...
    
    @staticmethod
    def is_integer(): # -> Literal[True]:
        ...
    
    @staticmethod
    def is_binary(): # -> Literal[True]:
        ...
    


BooleanSet = BinarySet
