"""
This type stub file was generated by pyright.
"""

from pyomo.core.kernel.base import ICategorizedObject

class ISOS(ICategorizedObject):
    """
    The interface for Special Ordered Sets.
    """
    __slots__ = ...
    variables = ...
    weights = ...
    level = ...
    def items(self): # -> zip[tuple[Any, Any]]:
        """Iterator over the sos variables and weights as tuples"""
        ...
    
    def __contains__(self, v): # -> Literal[True] | None:
        """Check if the sos contains the variable v"""
        ...
    
    def __len__(self): # -> int:
        """The number of members in the set"""
        ...
    


class sos(ISOS):
    """A Special Ordered Set of type n."""
    _ctype = ISOS
    __slots__ = ...
    def __init__(self, variables, weights=..., level=...) -> None:
        ...
    
    @property
    def variables(self): # -> tuple[Any, ...]:
        ...
    
    @property
    def weights(self): # -> tuple[int, ...] | tuple[Any, ...] | None:
        ...
    
    @property
    def level(self): # -> int:
        ...
    


def sos1(variables, weights=...): # -> sos:
    """A Special Ordered Set of type 1.

    This is an alias for sos(..., level=1)"""
    ...

def sos2(variables, weights=...): # -> sos:
    """A Special Ordered Set of type 2.

    This is an alias for sos(..., level=2).
    """
    ...

