"""
This type stub file was generated by pyright.
"""

from pyomo.common import Factory

logger = ...
class UnknownDataManager:
    def __init__(self, *args, **kwds) -> None:
        ...
    
    def available(self): # -> Literal[False]:
        ...
    


class DataManagerFactoryClass(Factory):
    def __call__(self, _name=..., args=..., **kwds): # -> Self | UnknownDataManager:
        ...
    


DataManagerFactory = ...
