"""
This type stub file was generated by pyright.
"""

def amplfunc_string_merge(amplfunc, pyomo_amplfunc): # -> LiteralString:
    """Merge two AMPLFUNC variable strings eliminating duplicate lines"""
    ...

def amplfunc_merge(env): # -> LiteralString:
    """Merge AMPLFUNC and PYOMO_AMPLFUNC in an environment var dict"""
    ...

