"""
This type stub file was generated by pyright.
"""

class ComponentDataSet:
    """ComponentDataSet(ctype)
    Domain validation class that accepts singleton or iterable arguments and
    compiles them into a ComponentSet, verifying that they are all ComponentDatas
    of type 'ctype.'

    Parameters
    ----------
        ctype: Either a single component type or an iterable of component types

    Raises
    ------
        ValueError if all of the arguments are not of a type in 'ctype'
    """
    def __init__(self, ctype) -> None:
        ...
    
    def __call__(self, x): # -> ComponentSet:
        ...
    
    def domain_name(self): # -> LiteralString:
        ...
    


